apiVersion: v1
kind: Service
metadata:
  name: {{ include "otc-cloudeye-exporter.fullname" . }}
  labels:
    {{- include "otc-cloudeye-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "otc-cloudeye-exporter.selectorLabels" . | nindent 4 }}